# Generated by Django 4.2.3 on 2023-09-26 12:29

import blogapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[blogapp.models.validatedate]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(blank=True, default='   ', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='idu',
            field=models.CharField(default='ooo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(blank=True, default='   ', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
