# Generated by Django 4.2.3 on 2023-09-26 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_bloguser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='social_media',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='linked_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='settings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
