# Generated by Django 4.2.3 on 2023-09-28 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_bloguser_social_media_bloguser_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='images/dp'),
        ),
    ]
