# Generated by Django 4.1.10 on 2023-09-29 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_like_alter_blog_author_alter_bloguser_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='relationship',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('U', 'Unmarried'), ('D', 'Divorced'), ('W', 'Widowed'), ('I', 'In a Relationship'), ('N', 'Not Interested')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3000), django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True),
        ),
    ]
