# Generated by Django 4.2.3 on 2023-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_bloguser_relationship_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='vip',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
