# Generated by Django 4.2.3 on 2023-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_bloguser_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='smarttransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.CharField(default='ooo', max_length=10)),
                ('idu', models.CharField(blank=True, max_length=10, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
