# Generated by Django 4.1.10 on 2023-10-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_smarttransaction_status_alter_smarttransaction_idc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarttransaction',
            name='transaction_st_tm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
