# Generated by Django 4.1.10 on 2023-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_rename_transaction_st_tm_smarttransaction_transaction_dt_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarttransaction',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
