# Generated by Django 4.1.10 on 2023-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_smarttransaction_razor_pay_payment_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smarttransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='smarttransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smarttransaction',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3),
        ),
    ]
